# Generated by Django 2.2.1 on 2019-05-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=31, verbose_name='名称')),
                ('intro', models.CharField(max_length=511, verbose_name='介绍')),
            ],
            options={
                'verbose_name_plural': '学科',
                'db_table': 'tb_subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('gender', models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性别')),
                ('birth', models.DateField(null=True, verbose_name='出生日期')),
                ('intro', models.CharField(default='', max_length=511, verbose_name='')),
                ('good_count', models.IntegerField(default=0, verbose_name='好评数')),
                ('bad_count', models.IntegerField(default=0, verbose_name='差评数')),
                ('photo', models.CharField(max_length=255, verbose_name='照片')),
                ('subject', models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.PROTECT, to='vote.Subject', verbose_name='所属学科')),
            ],
            options={
                'verbose_name_plural': '老师',
                'db_table': 'tb_teacher',
            },
        ),
    ]
